### ISSUE TITLE
Cursor disappears, particularly on Discourse forums

### ISSUE THREAD

**Issue by colinl** [BrowserWorks/waterfox#1004]
**Describe the bug**
After hitting Reply on a forum using Discourse (https://www.discourse.org/) the cursor does not appear in the edit window.  Typing works but the cursor is not visible.  Clicking away from Waterfox and back shows the cursor, though it disappears after a while though I have not tied down exactly what makes it disappear.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a topic on a discourse forum to which one is logged in .
2. Click Reply at the bottom of the topic
3. The new post field opens but there is no cursor visible.

**Expected behavior**
A cursor should appear

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.10

**Additional context**
Waterfox 56.2.10 (64-bit)

I see this effect on both the node-red and grafana forums (https://discourse.nodered.org and https://community.grafana.com) as well as the discourse demo forum https://try.discourse.org/
Unfortunately I have not been able to find a forum that does not require logging in in order to reply so that others can more easily confirm this, however one can either create and account at the demo forum at https://try.discourse.org/ or sign in with social media.
The only report of note in the web console is 
`This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!`
but I suspect that is not related.

Firefox 67.0 does not show the problem.

**Comment by grahamperrin** [comment]
> Clicking away from Waterfox and back shows the cursor,

When I lose sight of the pointer: 

1. <kbd>Alt</kbd>-<kbd>Tab</kbd>
2. <kbd>Alt</kbd>-<kbd>Tab</kbd>

KDE Plasma, FreeBSD-CURRENT. 

I see the symptom maybe a few times per week, but I've never paid enough attention to tell whether the issue is more likely to occur with Waterfox than with other applications. From now on, I'll pay attention.

**Comment by grahamperrin** [comment]
PS sorry, now I see the issue – **the cursor**, not the pointer. 

Consistently reproducible with Waterfox Classic on FreeBSD-CURRENT, not reproducible with 68.0a1. 

Mozilla Discourse can be used with a Firefox account. 

1. https://discourse.mozilla.org/
2. view any topic that's open to replies
3. either (a) click **Reply** or (b) select part of a post then click **Quote**

Bonus: https://discourse.mozilla.org/read

**Comment by ticalc-travis** [comment]
I'm seeing the same issue with the forums on developers.meethue.com, which appears to use the Discourse forum system (or at least it looks similar to the discourse.mozilla.org one). I only started noticing this today, after recently having upgraded to WF 56.2.11.

In addition to switching focus away from WF and back making the cursor return, clicking somewhere else on the page and back on the input field also gets it back. While the cursor is invisible, text selections are also invisible. It is apparently possible to select text with the keyboard or mouse, but the selection is completely invisible along with the cursor. Weird.

This is Ubuntu 16.04.6 running in the i3 window manager.

**Comment by terrypin999** [comment]
Before seeing this thread a few minutes ago I posted about a similar issue here:
https://github.com/MrAlex94/Waterfox/issues/1049

In my case, clicking outside WF did not resolve it.

Interestingly, when I came to post here, the text cursor was AWOL and clicking elsewhere and returning caused its return. Possibly an unrelated issue?

**Comment by grahamperrin** [comment]
https://github.com/MrAlex94/Waterfox/issues/1049#issuecomment-536285722 suggests use of mozregression

**Comment by hawkeye116477** [comment]
I've Moz://a account, so I played with it little.

**Mozregression result:**
* Last bad: 2019-01-09 10:15:38.299000 (1f5e1707e04e715ec63dab154efca792e2b38cb2)
* First good: 2019-01-09 16:49:50.385000 (26808f3dc0feb87880648c54ba23495d00457287)

Puslog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=1f5e1707e04e715ec63dab154efca792e2b38cb2&tochange=26808f3dc0feb87880648c54ba23495d00457287

I guess that's the fix => https://bugzilla.mozilla.org/show_bug.cgi?id=1450055

**Comment by ticalc-travis** [comment]
I've noticed that after posting a comment on Reddit the cursor continues to appear overlaid at an arbitrary place on the page near where the comment was written, even though there is no input element visible anymore. Could that symptom be related to this bug?

**Comment by grahamperrin** [comment]
Meta, tracking: #538
 
@ticalc-travis reproducible with Waterfox Classic 56.2.14 in safe mode?

Do you use Reddit Enhancement Suite and if so, which version?

**Comment by ticalc-travis** [comment]
Yes, it seems to reproduce in 56.2.14 safe mode as well. No Reddit Enhancement Suite installed (yet). As with the original mentioned behavior, it seems to return to normal if I remove and then reinstate focus to the affected Waterfox window.

**Comment by grahamperrin** [comment]
Old Reddit, or new?

**Comment by ticalc-travis** [comment]
Is that controlled by the “opt out of the redesign” option in the user settings? That appears to be off.

**Comment by grahamperrin** [comment]
Yes, 

> “opt out of the redesign” option in the user settings? That appears to be off.

– so the preference is the redesign (the new). 

@ticalc-travis ▶ https://old.reddit.com/r/sandbox/comments/ddzmqs/possible_issue_with_or_affecting_pointers_at/ for you tell whether you can reproduce symptoms with old Reddit. If so, please add a screenshot – or ideally, a screen recording (a recording may be more likely to capture the pointer in a wrong state). With early test results I can not reproduce the symptoms – I'll add a screen recording to the Reddit post – so I suspect that whatever's bugging you is **not** related to this reproducible issue #1004

If that post in the sandbox is weeded, then aim for any recent post under https://www.reddit.com/r/sandbox/new/

**Comment by hawkeye116477** [comment]
In case of disappearing cursor, that problem was solved on 2019.10.

**Comment by colinl** [comment]
Yes, I noticed it no longer happens, many thanks to whoever sorted that.  Is there still an issue in other situations?  If not then this can be closed.
