### ISSUE TITLE
Waterfox has trouble refreshing content without refreshing entire page

### ISSUE THREAD

**Issue by mikeloeven** [BrowserWorks/waterfox#195]
I have been having some scripting issues since the last waterfox update. I Experiencing Script hangs and some issues with JS based websites that rely on scripts to refresh content not being able to refresh the page without manually refreshing the page.

One of the sites this happens on is Ebay which is very annoying. essentially clicking on a link will appear to do absolutely nothing until you refresh the page or forcibly open the link in a new tab or window. Yes I have done basic troubleshooting clearing cookies and cache files.

**Comment by shalance** [comment]
Maybe related with https://github.com/gorhill/uBlock/issues/2947 ?

I was having exactly the same problem with eBay in Firefox and it was related to the new extension system. The issue has been solved uninstalling the WebExtensions add-ons and going back to XUL/XPCOM versions, so **do not mix WebExtensions and XUL/XPCOM add-ons**.

That's why I have decided it was time to forget about Firefox. I have switched to Waterfox, now that Mozilla is going to remove XUL/XPCOM add-on support. Everything works flawless now.

**Comment by mikeloeven** [comment]
Seems like its a known issue with regular FF as well disabling Ublock on eBay did not resolve the issue. Also if there is a conflict between webextensions and xul/xpcom this is something that should be investigated and recitified as going forward waterfox will need to support both.

Also is there any reliable way to tell which extensions are legacy and which have been updated to webextensions?

**Comment by mikeloeven** [comment]
So looks like you may have been right so disabling ublock in the addons menu worked but not disabling it on the page ?? 

any way downloaded the most recent experimental build of ublock from the git selecting the legacy build and the problem resolved it's self thanks for catching this I never would have thought ublock was the issue considering i had already tried toggling it earlier just apparently not all the way off :P

**Comment by grahamperrin** [comment]
@mikeloeven please review with updated extensions and a current release of Waterfox. Can this issue be closed?

**Comment by grahamperrin** [comment]
Review time. Close this?
