### ISSUE TITLE
waterfox: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by NuxRo** [BrowserWorks/waterfox#205]
Hello,

I'm on latest version of CentOS (7) and I am getting this error when trying to run Waterfox:
waterfox: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

Any chance you can build it with a lower glibc so it can run on more platforms?

**Comment by hawkeye116477** [comment]
@NuxRo I have fixed version of Waterfox on my apt repository. If CentOS using deb packages, then you can download it, otherwise you must probably wait for Alex when he publish official fixed version.
Fix is already on GitHub, 6 days ago added, https://github.com/MrAlex94/Waterfox/commit/7ff595a6db0433d643fdee65141828e8134cf541.

**Comment by br4nnigan** [comment]
Probably the same as this issue? https://github.com/MrAlex94/Waterfox/issues/186

**Comment by br4nnigan** [comment]
seems to be fixed with 55.0.2.1

**Comment by NuxRo** [comment]
Nope,

/lib64/libc.so.6: version `GLIBC_2.18' not found.

I'm on 2.17. 

Not sure how Mozilla builds their stuff, but it runs everywhere, do they say how they do it? Could help.

**Comment by br4nnigan** [comment]
For me it does work. I'm on Ubuntu though.

**Comment by hawkeye116477** [comment]
@NuxRo Type `about:buildconfig` and you will see :smile:.
Could it be useful -> `--enable-stdcxx-compat `?

**Comment by NuxRo** [comment]
Indeed, ff has that.

**Comment by joske** [comment]
/lib64/libc.so.6: version `GLIBC_2.18' not found.

same issue on RHEL 7.1. Only 2.17 is found.

**Comment by MrAlex94** [comment]
This should be fixed now, as I switched to a more compatible toolchain version :-).

**Comment by NuxRo** [comment]
Version 56.0.41 that I've just tried now still doesn't run:

./waterfox
XPCOMGlueLoad error for file /home/user/waterfox/libxul.so:
/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/user/waterfox/libxul.so)
Couldn't load XPCOM.

**Comment by MrAlex94** [comment]
How old is your system? The GNU C library 2.18 was released [2013-08-12](https://sourceware.org/ml/libc-alpha/2013-08/msg00160.html).

**Comment by NuxRo** [comment]
This is CentOS 7, the latest version of CentOS (and RHEL).

Firefox, Seamonkey, Vivaldi, Chrome etc all work just fine btw. I think Mozilla builds their stuff on the CentOS 6 stack.
