### ISSUE TITLE
(Auto-) Update via browser doesn't work

### ISSUE THREAD

**Issue by Striker243** [BrowserWorks/waterfox#3450]
What happened?

Problem description: 
The update function of the browser doesn't work as intended. I have the browser set to "Check for updates but let you choose to install them" and this works fine till a new update is found. Then I get notified and get send to the download page for the manual update without the possibility to directly update inside the browser (see attached picture). I can set it to "Automatically install updates" but after pressing F5 to reload it resets back to "Check for updates..".
The problem has existed for a long time but I always thought it is a general bug but when I recently looked through reddit and Github I noticed there were no related reports and started a search on my system.

Expected behaviour:
When getting notified about a new update, it should be possible to click "Update to G###" without needing to download the installer, closing the program and updating manually.

Conducted tests with version G6.0.12 & G.6.0.13:
- creating a new profile (no update possible: means update only possible via downloading the installer)
- uninstalling and reinstalling Waterfox (no update possible)

Then I copied the profile folder into a Win10 VM and tested there:
- copying the profile 1:1 into the VM (update possible: means I could update via the browser)
- copying said profile back (in the hope something got fixed)(no update possible)
- copying the "updates.xml" from "C:\ProgramData\Waterfox-UUID" in the VM back (no update possible)(though the file listed an error, see content of "updates.xml" in the log output)
- testing with and without the Maintenance Service of Mozilla Firefox (update possible either way)

I hope my description is comprehensible and someone finds out where the update process fails.
Thanks in advance :)
![About Waterfox](https://github.com/BrowserWorks/Waterfox/assets/14137245/a5d0c961-f317-49e8-b4d2-366672398c11)

![Waterfox Settings Update](https://github.com/BrowserWorks/Waterfox/assets/14137245/ad0447f4-7653-4741-bd89-837030432b74)

### Reproducible?

- [X] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

G6

### What platform are you seeing the problem on?

Windows

### Relevant log output

```shell
<?xml version="1.0"?><updates xmlns="http://www.mozilla.org/2005/app-update"><update xmlns="http://www.mozilla.org/2005/app-update" appVersion="115.11.0" buildID="20240424110000" channel="release" detailsURL="https://www.waterfox.net/docs/releases/G6.0.13" displayVersion="G6.0.13" installDate="1714309303893" isCompleteUpdate="true" name="Waterfox G6.0.13" previousAppVersion="115.11.0" promptWaitTime="3600" serviceURL="https://aus1.waterfox.net/update/Waterfox/G6.0.12/WINNT_x86_64/release/Windows_NT%2010.0.0.0.19045.3324%20(x64)/ISET:SSE4_2,MEM:8092/default/default/update.xml?force=1" type="major" statusText="Install Failed" foregroundDownload="true"><patch size="73240877" type="complete" URL="https://cdn1.waterfox.net/waterfox/releases/G6.0.13/update/WINNT_x86_64/waterfox-G6.0.13.complete.mar" errorCode="91" finalURL="https://cdn1.waterfox.net/waterfox/releases/G6.0.13/update/WINNT_x86_64/waterfox-G6.0.13.complete.mar" selected="true" state="failed" hashFunction="SHA512" hashValue="38ab0ebffa2318da8312f21522ea70bb8da3f13103ce48e9e77246ab2deed540842811e17da393b2bccc10f04ab5d150049324203577d88ca32b9a8bb15f0a37" internalResult="0"/></update></updates>
```

**Comment by Fritz66** [comment]
I wanted to add that this happens to me as well.
I'm using Linux and Waterfox G6.0.14, and there actually is no update available.
Here is a short video that shows what happens when I try to update the browser: https://files.catbox.moe/vq046n.mp4

But the same thing happens when an update is actually available. I would expect it to work the same way as it does with the Tor browser, Mozilla browser, and Firefox ESR, and just download and install the update without opening the download page.

Since I'm not the only one experiencing this, I assume it's a bug.

**Comment by Siff3D** [comment]
I confirm that the same bug is present in G6.0.15 and G6.0.16. Like @Striker243 and @Fritz66, I did see it it in previous versions, but I have no record when it first appeared.

I'm hoping that this will be fixed soon :)

**Comment by Fritz66** [comment]
Any updates on this issue?

**Comment by Striker243** [comment]
Update on my situation:
Since version 6.5.1 (update from version 6.5.1 to 6.5.2) the auto-update works again, so it seems like the problem is solved (though I don't know what changed). From my side the issue could be closed, but I don't know if it persists for the other commenters above.

**Comment by Siff3D** [comment]
It works for me too - I also think that the ticket can be closed.

**Comment by Fritz66** [comment]
It still doesn't still work properly for me, so I would be happy to know how to disable that update notification.

**Comment by toasterking** [comment]
I also have this same problem in Waterfox 6.6.17 (64-bit) for Windows on 2 different PCs:

> I can set it to "Automatically install updates" but after pressing F5 to reload it resets back to "Check for updates..".
