### ISSUE TITLE
extensions.getAddons.cache.enabled false prevents addition of some types of extension to Firefox 56.0.2 and Waterfox 56.0.2; and may cause null appearances if changed to false after installing the extension

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#370]
## Preamble – possible context

Whilst this bug might be very obscure (for Firefox, I can find nothing like it in Bugzilla@Mozilla), I wonder whether it can help to understand why Waterfox – which differs from Firefox in its initial state for `extensions.getAddons.cache.enabled` – is, in some cases, not entirely successful in an attempt to import from Firefox. 

For clarity, import issues should (please) be kept separate from this issue. 

----

# The issue

## Brief description

If `extensions.getAddons.cache.enabled` is `false` then an attempt to install this extension in the normal way – from addons.mozilla.org – is impossible: 

- [Icon Effects](https://addons.mozilla.org/addon/icon-effects/)

– in the the pop-up, the 'Add' button will remain greyed-out.

## Steps

1. with Waterfox 56.0.2
2. create a new profile
3. use the profile
4. visit https://addons.mozilla.org/addon/icon-effects/
5. click 'Add to Firefox'
6. in the pop-up, observe progress of the download and verification routines

### Expected

- in the pop-up, presentation of the 'Add' button

### Actual result

- the 'Add' button remains greyed-out, unavailable

### Workaround

- change `extensions.getAddons.cache.enabled` from `false` to `true`
- at https://addons.mozilla.org/addon/icon-effects/ reload the page
- click 'Add to Firefox'
- in the pop-up, observe progress of the download and verification routines
- click 'Add'
- restart Waterfox
- for any extension that might be not compatible with multi-process (and Icon Effects is not), **again** restart Waterfox (Mozilla bug [1394225 - multiprocess (e10s) automatically enabled at launch after installing extensions that are not compatible with multiprocess](https://bugzilla.mozilla.org/show_bug.cgi?id=1394225))

### … and then, only if required

- change `extensions.getAddons.cache.enabled` from `true` to `false`
- where previously the name of the extension – _Icon Effects_ – was visible (at e.g. about:addons and about:support`) there appears the word _null_.

## A few screenshots

In chronological order: 

![2018-01-11 01 13 20](https://user-images.githubusercontent.com/192271/34804535-11462744-f671-11e7-82d1-ecf4fc944488.png)

![2018-01-11 01 13 50](https://user-images.githubusercontent.com/192271/34804541-149ca9e0-f671-11e7-9a24-f7a091a3a419.png)

![2018-01-11 01 17 21](https://user-images.githubusercontent.com/192271/34804556-214c4286-f671-11e7-8499-79f218f02aad.png)

![2018-01-11 01 17 43](https://user-images.githubusercontent.com/192271/34804559-2454cfd4-f671-11e7-9389-e2a8ed5d643f.png)

![2018-01-11 01 19 07](https://user-images.githubusercontent.com/192271/34804564-29470be2-f671-11e7-850a-90e92e438713.png)

An earlier shot, exemplifying a _(null)_ appearance after removing the extension: 

![2018-01-11 01 11 06](https://user-images.githubusercontent.com/192271/34804533-0c9b7dd4-f671-11e7-9e6e-7848cc438b1d.png)

## Screen recording

[2018-01-11 00:58.ogv.zip](https://github.com/MrAlex94/Waterfox/files/1620968/2018-01-11.00.58.ogv.zip)

## Test environment

FreeBSD-CURRENT

```text
$ date ; uname -v
Thu 11 Jan 2018 01:54:52 GMT
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
$ pkg info waterfox | grep -i version
Version        : 56.0.2
$ 
```

## Related

`extensions.getAddons.cache.enabled` features in recent: 

- [Connections to a lot of servers · Issue #270 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/270)
- [information from addons.mozilla.org (AMO) · Issue #300 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/300)

The _Icon Effects_ extension features in [All info in about:support is blank : waterfox](https://redd.it/7oukgm) – that, too, should be a separate issue.

**Comment by ElhemEnohpi** [comment]
Thanks for testing this. I had Icon Effects already in my profile, which I copied to the Waterfox profile folder rather than doing an import. It got the name "null", but it seems to be working ok. It does seem to be compatible with e10s as well, at least, I have e10s forced on and it seems ok.

The only problem I noticed then was that the info in "about:support" is blank. It happens even with the addon disabled, or in safe mode. As a work-around, I moved the addon file out of the extensions folder, restarted, moved it back in, and restarted again. After that, the info in "about:support" came back, although the addon is still labelled "null". More info in the last link above. I could open a separate issue if you'd like, but I assume it won't be a problem anymore if this one is fixed.

**Comment by grahamperrin** [comment]
#538

**Comment by Peacock365** [comment]
FIXED as of Waterfox 56.1.

_extensions.getAddons.cache.enabled_ shows **true** again.

**Comment by grahamperrin** [comment]
I have it open, not entirely fixed, for this part of the title:

> ## … may cause null appearances if changed to false after installing the extension

– probably an edge case. I'd like to take a closer look for myself when things are less busy. Thanks.

**Comment by grahamperrin** [comment]
> `extensions.getAddons.cache.enabled` shows true again.

Confirmed, thanks, but it seems that something else prevents addition of the extension; #1269
