### ISSUE TITLE
Unable to build gecko68

### ISSUE THREAD

**Issue by laniakea64** [BrowserWorks/waterfox#970]
Attempting to build latest gecko68 branch is failing at the end of configure stage, with this error -
```
File already read. Skipping: /media/gecko/waterfox/Waterfox/gfx/angle/targets/angle_common/moz.build
Traceback (most recent call last):
  File "/media/gecko/waterfox/Waterfox/configure.py", line 132, in <module>
    sys.exit(main(sys.argv))
  File "/media/gecko/waterfox/Waterfox/configure.py", line 43, in main
    return config_status(config)
  File "/media/gecko/waterfox/Waterfox/configure.py", line 127, in config_status
    return config_status(args=[], **encode(sanitized_config, encoding))
  File "/media/gecko/waterfox/Waterfox/python/mozbuild/mozbuild/config_status.py", line 143, in config_status
    definitions = list(definitions)
  File "/media/gecko/waterfox/Waterfox/python/mozbuild/mozbuild/frontend/emitter.py", line 173, in emit
    for out in output:
  File "/media/gecko/waterfox/Waterfox/python/mozbuild/mozbuild/frontend/reader.py", line 885, in read_topsrcdir
    for r in self.read_mozbuild(path, self.config):
  File "/media/gecko/waterfox/Waterfox/python/mozbuild/mozbuild/frontend/reader.py", line 1052, in read_mozbuild
    raise bre
mozbuild.frontend.reader.BuildReaderError:
==============================
FATAL ERROR PROCESSING MOZBUILD FILE
==============================
The error occurred while processing the following file:
    /media/gecko/waterfox/Waterfox/browser/components/migration/moz.build
The error was triggered on line 25 of this file:
    'ProfileMigrator.jsm',
An error was encountered as part of executing the file itself. The error appears to be the fault of the script.
The error as reported by Python is:
    ['UnsortedError: An attempt was made to add an unsorted sequence to a list. The incoming list is unsorted starting at element 3. We expected "MigrationUtils.jsm" but got "WaterfoxProfileMigrator.jsm"\n']
*** Fix above errors and then restart with\
               "./mach build"
client.mk:111: recipe for target 'configure' failed
make[1]: *** [configure] Error 1
```

**Comment by MrAlex94** [comment]
Sorry I've fixed this locally. You just have to place the files in
alphabetical order.

**Comment by laniakea64** [comment]
> You just have to place the files in alphabetical order.

Thanks, that fixed this error and got it to pass configure.  But build still fails.  I think the error I'm now getting is same as https://github.com/MrAlex94/Waterfox/issues/939

**Comment by laniakea64** [comment]
Closing this since the issue in the original description is fixed by https://github.com/MrAlex94/Waterfox/commit/aa7a630bae4a076bad4a0365d3f9e8191b4f4d11 .  The remaining issue (gpsd-related failure) would better be addressed in #939.
