### ISSUE TITLE
V68: fails with 'Illegal instruction'

### ISSUE THREAD

**Issue by HubAl49** [BrowserWorks/waterfox#995]
**Describe the bug**
Waterfox v68 fails immediately with message 'Illegal instruction' - no other info, or anything obvious in the log files.

**To Reproduce**
Run 'waterfox-alpha'

**Expected behavior**
Sould start

**Desktop (please complete the following information):**
 - OS: Artix Linux
 - Version 4.19.44-1-lts

**Additional context**

From looking around the web, it seems that this may be caused by the program's code being incompatible with my desktop PC's CPU, which is an AMD Athlon Dual Core 4850e.

Waterfox v56 doesn't have this problem.

Here's the output from running gdb, if it's of any use (sorry, can't figure out how to get the 'code' tags  working properly) -

Reading symbols from waterfox-alpha...
(No debugging symbols found in waterfox-alpha)
(gdb) run
Starting program: /usr/bin/waterfox-alpha 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffeba48700 (LWP 31330)]
[Thread 0x7fffeba48700 (LWP 31330) exited]
[Detaching after fork from child process 31331]
[New Thread 0x7fffeba48700 (LWP 31332)]
[New Thread 0x7fffea6e1700 (LWP 31333)]
[New Thread 0x7fffe9aff700 (LWP 31334)]
[New Thread 0x7fffe9e25700 (LWP 31336)]
[New Thread 0x7fffe5cff700 (LWP 31337)]
[New Thread 0x7fffe5b00700 (LWP 31338)]
[New Thread 0x7fffe5ea8700 (LWP 31339)]
[New Thread 0x7fffe5e67700 (LWP 31340)]
[New Thread 0x7fffe5901700 (LWP 31341)]
Thread 10 "Link Monitor" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7fffe5e67700 (LWP 31340)]
0x000055555558910d in mozilla::SHA1Sum::finish(unsigned char (&) [20]) ()
(gdb) c
Continuing.
Thread 10 "Link Monitor" received signal SIGILL, Illegal instruction.
0x00007ffff7f8636f in raise () from /usr/lib/libpthread.so.0
(gdb) c
Continuing.
[1]+  Stopped                 gdb waterfox-alpha

I don't have this problem running Waterfox v68 on my netbook, which has an Intel Atom N450 CPU.

**Comment by grahamperrin** [comment]
> … AMD Athlon Dual Core 4850e. …

I know next to nothing about AMD, how does yours compare with (for example) <https://www.mozilla.org/en-US/firefox/68.0beta/system-requirements/>?

**Comment by HubAl49** [comment]
Hi Graham. Many thanks for the reply.

I know nothing about Intel ! However the details on the page you quote are identical to those on the equivalent page for FX 56 (on which Waterfox 56 is based?). And, as mentioned above, the problem doesn't happen with that version 56 of Waterfox.

**Comment by ilu33** [comment]
Having the same problem on AMD Phenom II. Firefox 67.0b10 works without a problem, just tried latest nightly FF 69 - works without problem too. And my gtk and libpango are not up to par (yet), that obviously doesn't matter.

Those AMD processors are actually quite popular in some user groups because they are the latest processors without any so-called "management engine".

**Comment by Squall-Leonhart** [comment]
cpu's lacking ssse3 and sse4

**Comment by HubAl49** [comment]
Looks like this issue has been fixed in commit 85165bf on 24/06/19, with '-march=core2' changed to '-march=x86-64'. 
Thank you!
Will await the next binary release to confirm that all is now OK, then close the issue.

Edit 1: just noticed the additional '-msse3' compile switch in the .mozconfig file. As my processor doesn't appear to support SSE3, I guess that the issue hasn't been fixed completely, at least not in my case.

Edit 2: Ignore 'Edit 1' above. The AMD 4850e CPU does in fact support SSE3, but the diagnostic CPU data lists this as 'pni' instead - obvious really!

**Comment by ilu33** [comment]
Downloaded the alpha again today but still not working on Phenom II 955x4. 
FF Nightly 71 doesn't have that problem. Is the  '-msse3' compile switch @HubAl49 mentioned really necessary? Why exclude users of older but very well working computers?

**Comment by MrAlex94** [comment]
I was under the assumption all x86-64 processors support SSE3. Plus I haven’t yet released any updated builds with the new flags, so what do you mean still not working?

**Comment by ilu33** [comment]
Last version I tried was downloaded in June, from HubAI49's comment I deducted that changes were made - I can't identify the exact waterfox version I downloaded today because it does not run :-)

If you haven't gotten to fixing it, no problem - I'll try again next month.

Edit: Actually, you are right, @Squall-Leonhart was wrong - the Phenom II supports SSE3 and SSE 4a - so the "illegal instruction" error must have another reason. How to debug?

**Comment by Squall-Leonhart** [comment]
Reread, i said SS**S**E3, and SSE4**a** is not SSE4 (SSE4a is an AMD subset of 4)
the Core2 March type optimises the code with SSSE3 in mind.

Phenom II does not support either.

Go and sit in the corner and be wrong.

**Comment by grahamperrin** [comment]
> I know next to nothing about AMD

but the invitation to wear a pointy D hat was irresistable so I allowed [automated correction](https://addons.mozilla.org/addon/british-english-dictionary-2/) (irresistible) to my wrong spelling and brought Wikipedia out of a corner because everyone knows that Wikipedia is _never_ wrong ;-)

FWIW

- https://wikipedia.org/wiki/Streaming_SIMD_Extensions
- https://wikipedia.org/wiki/SSE2
- https://wikipedia.org/wiki/SSE3 (third iteration)
- https://wikipedia.org/wiki/SSSE3 (fourth iteration)
- https://wikipedia.org/wiki/SSE4 (fifth iteration, I guess)
- https://wikipedia.org/wiki/SSE4#SSE4a

– and last but not least: 

- https://wikipedia.org/wiki/Phenom_II with **SSE4a** listed against five of the five core types. 

> … SSSE3 … SSE4a … Phenom II does not support either. 
> 
> Go and sit in the corner and be wrong.

Naughty step for editors of Wikipedia?

**Comment by Squall-Leonhart** [comment]
Context matters:
_"Is not SSE4"_ is taken when _"Does not support either"_ is provided, so the Phenom supports SSE4a, but not SSSE3 and SSE4,
_"Is not SSE4"_ is the last qualifier provided in that line since it retains context to the original comment being negated by the wrong user above.

English is a nightmare when you use it to its fullest.

**Comment by grahamperrin** [comment]
> … English is a nightmare when you use it to its fullest.

OK … when you wrote this: 

>> i said SS**S**E3, and SSE4**a** is not SSE4 (SSE4a is an AMD subset of 4)
the Core2 March type optimises the code with SSSE3 in mind.
>> 
>> Phenom II does not support either.

– with those emphases – I thought you meant that Phenom II does not support either SSSE3 or SSE4a. Maybe rererereedit <https://github.com/MrAlex94/Waterfox/issues/995#issuecomment-528674339>?

**Comment by MrAlex94** [comment]
@ilu33, does Waterfox now launch on the new builds?

**Comment by ilu33** [comment]
The original error is gone, so that problem seems solved. Now I'm getting (on Debian 9/stretch.):
```
/opt/waterfox68/waterfox
XPCOMGlueLoad error for file /opt/waterfox68/liblgpllibs.so:
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /opt/waterfox68/liblgpllibs.so)
Couldn't load XPCOM.
```

**Comment by laniakea64** [comment]
@ilu33 That looks related to https://github.com/MrAlex94/Waterfox/issues/1128
